// lrcplayer-android-sdk 独立构建配置
// 作为模块被其他项目 include 时本文件不生效(由宿主项目的 settings 接管)
pluginManagement {
    plugins {
        id 'com.android.library' version '8.5.2'
        id 'org.jetbrains.kotlin.android' version '1.9.24'
    }
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = 'lrcplayer-android-sdk'
